dist: focal
language: python
python:
- '3.8'

install:
- pip3 install --upgrade pip
- pip3 install -r dev-requirements.txt

script:
- python3 -m unittest -v
- flake8

git:
  depth: false
  quiet: true
branches:
  only:
  - master
  - /^2020-Q3\./
notifications:
  email:
    on_success: always
    on_failure: always
